//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class transacciones
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public int IDarticulo { get; set; }
        public System.DateTime fecha { get; set; }
        public int cantidad { get; set; }
        public int monto { get; set; }
    }
}
